export const ONCHANGE_INPUT = 'ONCHANGE_INPUT';
export const ONCLICK_BUTTON_GO = 'ONCLICK_BUTTON_GO';
export const ONCLICK_USER = 'ONCLICK_USER';
export const ONCHANGE_TEXTAREA = 'ONCHANGE_TEXTAREA';
// send url request
export const SEND_URL_REQUEST = 'SEND_URL_REQUEST';
export const SEND_URL_SUCCESS = 'SEND_URL_SUCCESS';
export const SEND_URL_ERROR = 'SEND_URL_ERROR';
